# -*- coding: utf-8 -*-
# :Project:   pymeshfix -- Configuration to build and upload Linux wheels to PyPI
# :Author:    Alex Kaszynski <akascap@gmail.com>
# :License:   MIT License

# borrowed parts from
# https://github.com/python-rapidjson/python-rapidjson/blob/master/.appveyor.yml

# Builds wheels for Linux using cibuildwheel, inside the manylinux1 Docker image.
# builds 64-bit Python2.7, Python3.5, Python3.6, Python3.7

dist: xenial

matrix:
  include:
    - sudo: required
      language: python
      python: "3.6"
      services:
        - docker
      env: PIP=pip


# for reference, these are the python installs on
# quay.io/pypa/manylinux1_x86_64
# cp27-cp27m
# cp27-cp27mu
# cp34-cp34m
# cp35-cp35m
# cp36-cp36m
# cp37-cp37m

# need to skip 32-bit development
# quay.io/pypa/manylinux1_i686

# CIBW_SKIP
# must skip cp27-cp27m and cp37-cp37m
# cp37-cp34m has a vtk bug that I'm not willing on fixing

env:
  global:
    - CIBW_BEFORE_BUILD="pip install numpy==1.15.0; pip install cython; yum install libXt -y"
    - CIBW_TEST_REQUIRES="pytest"
    - CIBW_TEST_COMMAND="pytest {project}/tests"
    - CIBW_SKIP="cp27-cp27m-manylinux1_x86_64 cp34-* *manylinux1_i686*"
    - TWINE_USERNAME=akaszynski
      # Note: TWINE_PASSWORD is set in Travis settings

before_install:
  # configure a headless display
  - git clone --depth 1 git://github.com/pyvista/gl-ci-helpers.git
  - source ./gl-ci-helpers/travis/setup_headless_display.sh

script:
  - $PIP install cibuildwheel==0.10.0
  # Test
  - cibuildwheel --output-dir wheelhouse
  # Install
  - pip install .
  # Make documentation
  - cd ./docs;
  - make html;
  - set -e;
  - make html;
  - cd ..;
  # TODO: @banesullivan can set this up:
  # - doctr deploy --built-docs ./docs/_build/html/ .;
  # Deploy on tags
  - if [ "${TRAVIS_TAG:-}" != "" ]; then
      python3 setup.py sdist;
      cp dist/*.tar.gz wheelhouse/;
      pip3 install twine;
      python3 -m twine upload --skip-existing wheelhouse/*;
    fi

notifications:
  email: false
