# -*- coding: utf-8 -*-
# :Project:   pymeshfix -- Configuration to build and upload Linux wheels to PyPI
# :Author:    Alex Kaszynski <akascap@gmail.com>
# :License:   MIT License

# borrowed parts from
# https://github.com/python-rapidjson/python-rapidjson/blob/master/.appveyor.yml

# Builds wheels for Linux using cibuildwheel, inside the manylinux1 Docker image.
# builds 64-bit Python2.7, Python3.5, Python3.6, Python3.7

dist: xenial

matrix:
  include:
    - sudo: required
      language: python
      python: "3.6"
      services:
        - docker
      env: PIP=pip
    - os: osx
      osx_image: xcode8.3

env:
  global:
    - CIBW_BEFORE_BUILD_LINUX="pip install numpy==1.15.0; pip install cython;pip install pymeshfix; yum install libXt -y"
    - CIBW_BEFORE_BUILD_MACOS="pip install numpy==1.15.0; pip install cython; pip install pymeshfix"
    - CIBW_TEST_REQUIRES="pytest"
    - CIBW_TEST_COMMAND="pytest {project}/tests"
    - CIBW_SKIP="cp27-cp27m-manylinux1_x86_64 cp34-* *manylinux1_i686*"
    - TWINE_USERNAME=akaszynski
      # Note: TWINE_PASSWORD is set in Travis settings
    # Doctr deploy key for pyvista/tetgen
    - secure: "MVzgh3/QFmF1KibL1ANEUfsD1id7ab3OGh8k13tl0SyykO8VgVFzNOEqvdfueB38zR/Ie1/JhD5m8UNLkcEYU8kcpYDIUS5i44/FGY1/9T3EDutVr4x3sZf3IfVG7Xs4RmeZCVGCSaWch/lK/+4YVZ8EM0b7HpltqVNWHI/a6Kgj1rLwPeV+tkg5Kcg2++W6DOL+26wP13A82jyQGI2Eb03x2HRQEwF3PePDniGFehEdNdMmuWldIQPEu29GoqWl8mOWjTRHvGi6MtMHpoqfBb0tbgSCAz7CjuxQAS9jvA4Jid3X8Zc87WLxxfGlV/UDNrLa2blODvYhTTdo+XoAJAZOfQ4ufXVoPCqoM5QS9fffewrX9MXhTXUkf4kYhfiWD45zjYULtGnWTfYaNmO1enmAtKDUgrBs1G02AtVktJHcQ5dCwf3NCmkO2EG4pAdAliSY0aAuBU1npE5USIbqm+RsUmploRL3Gd02HBRMWi+IeouTEZDrEhBrcNwcWqTuN5K0AjiqPyo9Wk3HB8KZxuvCpkhn3qbcDDK0Cw3AA4Ue/+kLm1uLklh3+fAgSmE9VgbolcdGqsb/cphoOkJ6Zrwy72WGjhyhh3clRRMIFHD9Ac5r9o9Y5XnX0HgkqlODAzVU0RtDigAWWekoO7OyIIB/zcRDV71lt+qOhO30PQ8="

before_install:
  # configure a headless display
  - git clone --depth 1 git://github.com/pyvista/gl-ci-helpers.git
  - source ./gl-ci-helpers/travis/setup_headless_display.sh


install:
  # Setup for python 3 wheels in Mac OS X
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      brew update
      brew upgrade python
      CFLAGS='-stdlib=libc++'
    fi;
  - pip3 install --upgrade cibuildwheel
  # for building docs in linux
  - |
    if [ "$TRAVIS_OS_NAME" != "osx" ]; then
      pip3 install -r requirements.txt
    fi;

script:
  - cibuildwheel --output-dir wheelhouse
    # Make documentation
  - |
    if [ "$TRAVIS_OS_NAME" != "osx" ]; then
      cd ./wheelhouse
      pip3 install tetgen-*-cp36-cp36m-manylinux1_x86_64.whl
      cd ../docs
      make html
      set -e
      make html
      cd ..
      doctr deploy --built-docs ./docs/_build/html/ .;
      set +x
    fi;
  # Deploy on tags
  - if [ "${TRAVIS_TAG:-}" != "" ]; then
      python3 setup.py sdist;
      cp dist/*.tar.gz wheelhouse/;
      pip3 install twine;
      python3 -m twine upload --skip-existing wheelhouse/*;
    fi

notifications:
  email: false
